name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security_tests:
    runs-on: ubuntu-latest

    steps:
    - name: clone the github repo on the runner
      uses: actions/checkout@v4

    - name: Use Node.js version 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: install program dependencies
      run: npm install
      
    - name: Run audit tests
      run: npm audit

  build_test:
    needs: security_tests
    runs-on: ubuntu-latest

    steps:
    - name: clone the github repo on the runner
      uses: actions/checkout@v4

    - name: Use Node.js version 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: install program dependencies
      run: npm install
      
    - name: Run all tests
      run: npm run test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_API_KEY }}
          api_key: ${{ secrets.SERVICE_KEY }}
          wait_deploy: true
