name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: clone the github repo on the runner
      uses: actions/checkout@v4

    - name: Use Node.js version 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: install program dependencies
      run: npm install
      
    - name: Run all tests
      run: npm run test

  security_tests:
    runs-on: ubuntu-latest

    steps:
    - name: clone the github repo on the runner
      uses: actions/checkout@v4

    - name: Use Node.js version 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: install program dependencies
      run: npm install
      
    - name: Run audit tests
      run: npm audit